name: Check Python Tests

on: [pull_request]

jobs:
  build:
    name: Tests Check
    runs-on: ubuntu-20.04
    steps:
      - name: clone-repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: install-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"
      - name: install-requirements
        run: python -m pip install -r requirements-develop.txt
      - name: tests-check
        run: bash tests-exec.sh
      - name: tests-coverage
        run: bash tests-coverage.sh
